// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Tres sidebars independientes, uno por sección del sitio:
 * - manualSidebar: Manual de Usuario (público general)
 * - administracionSidebar: Administración (usuarios con rol admin)
 * - desarrolladoresSidebar: Documentación técnica (sección reservada)
 *
 * Cada uno se genera automáticamente a partir de su carpeta en docs/,
 * respetando el orden definido en cada _category_.json y en el
 * "sidebar_position" de cada archivo .md.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  manualSidebar: [{type: 'autogenerated', dirName: 'manual-usuario'}],
  administracionSidebar: [{type: 'autogenerated', dirName: 'administracion'}],
  desarrolladoresSidebar: [{type: 'autogenerated', dirName: 'desarrolladores'}],
};

export default sidebars;
